corrections and additions for calculator
TimZib/EPAM-Tasks pull request #1
Opened 2021-11-28 10:29 UTC by TimZib

2021-12-01 07:28 UTC, rimus requested changes
Also I haven't seen negative cases.

2021-12-01 07:28 UTC, rimus commented on stage2-calculator/calculator.js
> +    if (typeof a === 'number' && typeof a === 'number') {
`typeof a === 'number'` is duplicated here. Parameter `b` is not checking.

2021-12-01 07:28 UTC, rimus commented on stage2-calculator/calculator.js
> +    if (typeof a === 'number' && typeof a === 'number') {
`typeof a === 'number'` is duplicated here. Parameter `b` is not checking.

2021-12-01 07:28 UTC, rimus commented on stage2-calculator/add-multiply.spec.js
> +    { a: 7, b: Number, sum: 46 },
Are all of your tests passing? :)

2021-12-01 07:28 UTC, rimus commented on stage2-calculator/add-multiply.spec.js
> +    { a: 7, b: 39, sum: 273 },
Are all of your tests passing? :)

2021-12-01 10:47 UTC, TimZib commented on stage2-calculator/calculator.js
> +    if (typeof a === 'number' && typeof a === 'number') {
That was a typo. 
if (typeof a === 'number' && typeof b === 'number')

2021-12-01 10:47 UTC, TimZib commented on stage2-calculator/calculator.js
> +    if (typeof a === 'number' && typeof a === 'number') {
That was a typo. 
if (typeof a === 'number' && typeof b === 'number')

2021-12-01 10:54 UTC, TimZib reviewed
Some answers

2021-12-01 10:54 UTC, TimZib commented on stage2-calculator/calculator.js
> +    if (typeof a === 'number' && typeof a === 'number') {
That was a typo. 
if (typeof a === 'number' && typeof b === 'number')

2021-12-01 10:54 UTC, TimZib commented on stage2-calculator/add-multiply.spec.js
> +    { a: 7, b: 39, sum: 273 },
Not all. All in one. Negative and positive scenarios.

2021-12-01 10:54 UTC, TimZib commented on stage2-calculator/add-multiply.spec.js
> +    { a: 7, b: Number, sum: 46 },
Not all. All in one. Negative and positive scenarios.

2021-12-02 11:46 UTC, rimus requested changes

2021-12-02 11:46 UTC, rimus commented on stage2-calculator/calculator.js
> +    if (typeof a === 'number' && typeof a === 'number') {
Why it still not fixed here? :)

2021-12-02 11:46 UTC, rimus commented on stage2-calculator/add-multiply.spec.js
> +  });
These it-blocks also can be put into sngle one with `forEach()`

2021-12-02 13:25 UTC, rimus approved these changes
Looks good.

2021-12-03 21:11 UTC, merged